# Generated by Django 4.2.4 on 2023-08-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('taskTitle', models.CharField(max_length=50)),
                ('taskDescription', models.TextField(max_length=500)),
                ('is_completed', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
