# Generated by Django 4.2.4 on 2023-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_taskmodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
