# Generated by Django 4.2.4 on 2023-08-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_taskmodel_category_taskmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
