# Generated by Django 4.2.4 on 2023-08-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_taskmodel_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskTitle',
            field=models.CharField(max_length=30),
        ),
    ]
