# Generated by Django 4.2.4 on 2023-08-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_filtermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterModel',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='filterId',
            field=models.IntegerField(default=1),
        ),
    ]
